### ISSUE TITLE
Is there a way to use different numbers of time points per sequence?

### ISSUE THREAD

**Issue by diego-doe** [lopatovsky/HMMs#1]
Hi,

I was wondering if there's a way to use different numbers of time points per sequence? Currently when I try to do this, the program complains that the list can't be converted to a numpy array. Apologies for raising this as an issue but I didn't know how to comment here.

Thanks.

Best regards,
DIego

**Comment by lopatovsky** [comment]
Hello Diego,

The project is still in the development phase and for now it only supports the numpy array.
However, the modification it needs to accept the list is not big, so I will consider the change. Perhaps it can be ready in couple of days. (I will inform you by closing the issue.)
On what data-set are you planning to use it?

Best,
Lukas Lopatovsky

**Comment by diego-doe** [comment]
Thanks! At the moment I was trying it out with synthetic data, but at some point the plan would be to try it on real data. Is there a way I can contact you? Would like to discuss.

Best,
Diego

**Comment by lopatovsky** [comment]
Hello, 
you can reach me at lopatovsky@gmail.com, we can set up some discussion there.

All the best,
Lukas

**Comment by lopatovsky** [comment]
The library is now supporting various lengths of the training vectors. In both models for Baum-welch and also for estimation calculation procedures.  So now it can be used numpy matrix or list of numpy vectors as the parameter. The program recognize them automatically.
